# Generated by Django 5.0.9 on 2024-09-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('resolution', models.CharField(max_length=50)),
                ('predicted_class', models.CharField(max_length=100)),
                ('prediction_probabilities', models.TextField()),
                ('image_data', models.BinaryField(max_length='max')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
