# Generated by Django 5.0.9 on 2024-09-13 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_rate', models.FloatField()),
                ('num_epochs', models.IntegerField()),
                ('kernel_size', models.CharField(max_length=10)),
                ('optimizer', models.CharField(max_length=50)),
                ('metrics', models.CharField(max_length=100)),
                ('batch_size', models.IntegerField()),
                ('num_kernels', models.IntegerField()),
                ('early_stopping', models.BooleanField()),
                ('validation_split', models.FloatField()),
                ('lr_scheduler_params', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('inserted_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
