# Generated by Django 4.2.16 on 2024-09-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelConfig',
            new_name='ParamsModelConfig',
        ),
    ]
