# Generated by Django 5.0.9 on 2024-09-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('val_loss', models.FloatField()),
                ('val_accuracy', models.FloatField()),
                ('training_loss', models.FloatField(default=0.0)),
                ('training_accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('batch_size', models.IntegerField(default=32)),
                ('num_epochs', models.IntegerField(default=10)),
                ('optimizer', models.CharField(default='Adam', max_length=50)),
                ('loss_curve_url', models.URLField(blank=True, null=True)),
                ('accuracy_curve_url', models.URLField(blank=True, null=True)),
                ('roc_curve_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'model_training_records',
            },
        ),
    ]
