# Generated by Django 5.0.9 on 2024-09-11 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_modelconfig_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='inserted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
